apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: cockroachdb
  name: cockroachdb
spec:
  containers:
    - args:
        - start-single-node
        - --insecure
        - --store=attrs=ssd,path=/var/lib/cockroach/
      image: cockroachdb/cockroach:latest-v23.1
      livenessProbe:
        exec:
          command:
            - curl
            - -f
            - http://localhost:8080/health?ready=1
        failureThreshold: 5
        periodSeconds: 3
        timeoutSeconds: 3
      name: cockroachdb
      ports:
        - containerPort: 26257
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/cockroach
          name: nakama-data
  restartPolicy: Never
  volumes:
    - name: nakama-data
      persistentVolumeClaim:
        claimName: nakama-data
