apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cockroachdb
  name: cockroachdb
spec:
  ports:
    - name: "26257"
      port: 26257
      targetPort: 26257
      protocol: UDP
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: UDP
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: 26257-tcp
      port: 26257
      targetPort: 26257
      protocol: TCP
  selector:
    io.kompose.service: cockroachdb
