apiVersion: agones.dev/v1
kind: GameServer
metadata:
  generateName: dev-meadow-game-server-
  annotations:
    agones.dev/dev-address: "192.168.0.159"
spec:
  ports:
    - name: default
      portPolicy: Static
      hostPort: 7001
      containerPort: 7654
      protocol: TCP
  health:
    initialDelaySeconds: 10
  template:
    spec:
      containers:
        - name: dev-meadow-game-server
          image: docker.io/chrisanicolaou/meadow-server:alpha
          resources:
            requests:
              memory: 64Mi
              cpu: 20m
            limits:
              memory: 64Mi
              cpu: 20m