
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: meadow-game-server-autoscaler
spec:
  fleetName: meadow-game-server
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 0
      maxReplicas: 10