apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\chris\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nakama
  name: nakama
spec:
  ports:
    - name: "7349"
      port: 7349
      targetPort: 7349
      protocol: UDP
    - name: "7350"
      port: 7350
      targetPort: 7350
      protocol: UDP
    - name: "7351"
      port: 7351
      targetPort: 7351
      protocol: UDP
    - name: 7349-tcp
      port: 7349
      targetPort: 7349
      protocol: TCP
    - name: 7350-tcp
      port: 7350
      targetPort: 7350
      protocol: TCP
    - name: 7351-tcp
      port: 7351
      targetPort: 7351
      protocol: TCP
    - name: "9100"
      port: 9100
      targetPort: 9100
      protocol: UDP
  selector:
    io.kompose.service: nakama
