apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: nakama
  name: nakama
spec:
  containers:
    - command:
        - /bin/sh
        - -ecx
        - "/nakama/nakama migrate up --database.address root@cockroachdb:26257 && exec /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257 --logger.level DEBUG --session.token_expiry_sec 7200          \n"
      image: docker.io/chrisanicolaou/meadow-nakama-server:dev
      imagePullPolicy: Always
      livenessProbe:
        exec:
          command:
            - /nakama/nakama
            - healthcheck
        failureThreshold: 5
        periodSeconds: 10
        timeoutSeconds: 5
      name: nakama
      ports:
        - containerPort: 7349
          protocol: TCP
        - containerPort: 7350
          protocol: TCP
        - containerPort: 7351
          protocol: TCP
        - containerPort: 9100
          protocol: TCP
  restartPolicy: Never
